function probabilities = gp_probability_discrete(data, responses, ...
          in_train, prior_covariances, inference_method, mean_function, ...
          covariance_function, likelihood, hypersamples)

  [means variances hypersample_weights] = ...
      estimate_latent_posterior_discrete(data, responses, in_train, ...
          prior_covariances, inference_method, mean_function, ...
          covariance_function, likelihood, hypersamples);

  num_predictions = numel(means);

  probabilities = ...
      reshape(exp(likelihood([], ones(num_predictions, 1), ...
                             means(:), variances(:))), ...
              size(means));
  probabilities = bsxfun(@times, probabilities, hypersample_weights);
  probabilities = sum(probabilities, 2);
  
end