function probabilities = gp_probability(data, responses, test, ...
          inference_method, mean_function, covariance_function, ...
          likelihood, hypersamples)

  [means variances hypersample_weights] = estimate_latent_posterior(data, ...
          responses, test, inference_method, mean_function, ...
          covariance_function, likelihood, hypersamples);

  posterior_means = means * hypersample_weights;
  posterior_variances = ...
      (variances + means.^2) * hypersample_weights - posterior_means.^2;
  
  num_test = size(test, 1);
  
  probabilities = exp(likelihood([], ones(num_test, 1), ...
          posterior_means, posterior_variances));
  
end