function [estimated_proportion proportion_variance] = ...
  random_sampling_estimate(data, responses, in_train, ...
    num_evaluations, inference_method, mean_function, ...
    covariance_function, likelihood, hypersamples, num_f_samples)

  test_ind = find(~in_train);
  r = randperm(numel(test_ind));

  in_train(test_ind(r(1:num_evaluations))) = true;

  [means covariances hypersample_weights] = ...
    estimate_latent_posterior(data, responses, in_train, inference_method, ...
      mean_function, covariance_function, likelihood, ...
      hypersamples, true);
  
  [estimated_proportion proportion_variance] = ...
    estimate_proportion(means, covariances, hypersample_weights, num_f_samples);
  
  num_train = sum(in_train);
  num_test = sum(~in_train);
  
  estimated_proportion = ...
    num_train / (num_train + num_test) * (mean(responses(in_train) == 1)) + ...
    num_test  / (num_train + num_test) * estimated_proportion;

  proportion_variance = ...
    num_test  / (num_train + num_test) * proportion_variance;

end