function [chosen_ind, utilities] = uncertainty_sampling(data, ...
          responses, train_ind, probability_function, ...
          base_selection_function, num_evaluations, verbose)

  % set verbose to false if not defined
  verbose = exist('verbose', 'var') && verbose;

  selection_objective_function = @(data, responses, train_ind) ...
      calculate_entropies(data, responses, train_ind, ...
                          base_selection_function(data, responses, train_ind), ...
                          probability_function);
  selection_functions{1} = @(data, responses, train_ind) ...
      maximum_value_selector(data, responses, train_ind, ...
                             selection_objective_function);

  utility_objective_function = @(data, responses, train_ind) ...
      -calculate_entropies(data, responses, train_ind, ...
                           base_selection_function(data, responses, train_ind), ...
                           probability_function);
  utility_function = @(data, responses, train_ind) ...
      maximum_utility_function(data, responses, train_ind, ...
                               utility_objective_function);

  lookahead = 1;

  [chosen_ind, utilities] = optimal_learning(data, responses, ...
          train_ind, utility_function, probability_function, ...
          selection_functions, lookahead, num_evaluations, verbose);

end
