function [estimated_proportions proportion_variances in_train] = ...
      random_sampling_estimate(data, responses, in_train, ...
                               prior_covariances, num_evaluations, inference_method, ...
                               mean_function, covariance_function, likelihood, hypersamples, ...
                               num_f_samples)
  
  estimated_proportions = zeros(num_evaluations, 1);
  proportion_variances = zeros(num_evaluations, 1);
  
  for i = 1:num_evaluations
    test_ind = find(~in_train);
    num_test = length(test_ind);
    
    r = randperm(num_test);
    in_train(r(1)) = true;
    
    [means covariances hypersample_weights] = estimate_latent_posterior(data, ...
        responses, in_train, prior_covariances, inference_method, ...
        mean_function, covariance_function, likelihood, hypersamples, true);
    
    [estimated_proportion proportion_variance] = ...
        estimate_proportion(means, covariances, hypersample_weights, num_f_samples);
    
    num_train = sum(in_train);
    
    estimated_proportions(i) = ...
        num_train / (num_train + num_test) * (mean(responses(in_train) == 1)) + ...
        num_test  / (num_train + num_test) * estimated_proportion;
    
    proportion_variances(i) = ...
        num_test  / (num_train + num_test) * proportion_variance;
    
    disp(['random sampling: ' num2str(i) ...
          ' of ' num2str(num_evaluations) ...
          ', current estimate: ' num2str(estimated_proportions(i)) ...
          ' +/- ' num2str(sqrt(proportion_variances(i)))]);
  end

end