function probabilities = gp_probability_discrete(data, responses, ...
          in_train, prior_covariances, inference_method, mean_function, ...
          covariance_function, likelihood, hypersamples)

  [means variances hypersample_weights] = ...
      estimate_latent_posterior_discrete(data, responses, in_train, ...
          prior_covariances, inference_method, mean_function, ...
          covariance_function, likelihood, hypersamples);
  
  posterior_means = means * hypersample_weights;
  posterior_variances = ...
      (variances + means.^2) * hypersample_weights - posterior_means.^2;
  
  test_ind = find(~in_train);
  num_test = numel(test_ind);
  
  probabilities = exp(likelihood([], ones(num_test, 1), ...
          posterior_means, posterior_variances));
  
end