function response_samples = independent_response_sampler(data, ...
          responses, train_ind, probability_function, num_samples)

  test_ind = identity_selector(responses, train_ind);
  num_test = numel(test_ind);

  probabilities = ...
      probability_function(data, responses, train_ind, test_ind);

  cdfs = cumsum(probabilities, 2);

  response_samples = repmat(responses, [1, num_samples]);
  response_samples(test_ind, :) = 1 + ...
      squeeze( ...
          sum( ...
              bsxfun(@gt, ...
                     rand(num_test, 1, num_samples), ...
                     repmat(cdfs, [1, 1, num_samples]) ...
                     ), ...
              2) ...
          );

end
