function [chosen_ind, utilities] = active_search(data, responses, ...
        train_ind, probability_function, probability_bound, ...
        num_evaluations, lookahead, verbose)

  % set verbose to false if not defined
  verbose = exist('verbose', 'var') && verbose;

  utility_function = @(data, responses, train_ind) ...
      count_utility(responses, train_ind);

  selection_functions = cell(lookahead, 1);
  for i = 1:lookahead
    selection_functions{i} = @(data, responses, train_ind) ...
        optimal_search_bound_selector(data, responses, train_ind, ...
            probability_function, probability_bound, i);
  end

  [chosen_ind, utilities] = optimal_learning(data, responses, train_ind, ...
          utility_function, probability_function, selection_functions, ...
          lookahead, num_evaluations, verbose);

end